1st module
js-tasks-ru/jsbasic-20210420_yuliya892 pull request #2
Opened 2021-05-06 06:56 UTC by kasuzame

Выполнены задания из первого модуля.

2021-05-06 06:57 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-05-06 14:52 UTC, SinimaWath requested changes

2021-05-06 14:52 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  else if (name.indexOf(" ") !== -1) {
indexOf - тут лишние, так как у тебя есть проверка includes выше

2021-05-06 14:52 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  else {return true;}
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return name !== null ....`

Это как раз тот случай

2021-05-06 14:52 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  else {return false;}
Давай упростим до: `return ...` без if

2021-05-06 14:52 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  else {return str;}
Этот else тут лишний, можно переписать без него:
```
if (...) {
  return ..
}

return ...
```

2021-05-06 15:57 UTC, kasuzame commented on 1-module/4-task/index.js
> +  else {return false;}
+

2021-05-06 15:58 UTC, kasuzame commented on 1-module/5-task/index.js
> +  else {return str;}
Ок

2021-05-06 15:58 UTC, kasuzame commented on 1-module/2-task/index.js
> +  else {return true;}
Немного по-другому переписала. Надеюсь, норм.

2021-05-06 15:58 UTC, kasuzame commented on 1-module/2-task/index.js
> +  else if (name.indexOf(" ") !== -1) {
Ок.

2021-05-07 12:53 UTC, SinimaWath requested changes

2021-05-07 12:53 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  else if (name.includes(' ')) {
else тут лишний - так как в первом условии у тебя уже есть return.

```
if () {
  return ...
}

if () {
 return ...
}

return ...
```

2021-05-07 12:53 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let lowerStr = str.toLowerCase();
lowerStr - это const ;)

2021-05-08 14:28 UTC, kasuzame commented on 1-module/4-task/index.js
> +  let lowerStr = str.toLowerCase();
Поняла, спасибо!

2021-05-08 14:28 UTC, kasuzame commented on 1-module/2-task/index.js
> +  else if (name.includes(' ')) {
Спасибо!

2021-05-08 19:40 UTC, SinimaWath approved these changes

2021-05-08 19:40 UTC, merged